version: "3"

services:
  nginx:
    image: nginx:alpine
    volumes:
      #- ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./laravel/public:/var/www/laravel/public
    ports:
      - 80:80
    depends_on:
      - phpfpm
  phpfpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    privileged: true
    command:
      - /sbin/init
      - start.sh
    volumes:
      - .:/app
      - ./laravel:/var/www/laravel
      - ./scripts/start.sh:/usr/local/bin/start.sh
    depends_on:
      - mysql
    env_file: .env
  mysql:
    image: mysql:8.0
    env_file: .env
    volumes:
      - ./mysql/volumes:/var/lib/mysql
    ports:
      - 4306:3306
